### ISSUE TITLE
MacOSX issues

### ISSUE THREAD

**Issue by jcldc** [teuben/nemo#10]
gnu compilers : 4.9.x

- configure ok.
- Nemo library seems to be compiled correctly
- FalcON does compile and run

BUT impossible to create a nemo binary,  exemple **mknemo tsf** cannot compile because compiler complains with message : 
```
ld: unknown option: --no-as-needed
collect2: error: ld returned 1 exit status
make: *** [tsf] Error 1
```
This bad compilation option comes from file **$NEMOLIB/makedefs** file...
```
#  Another option is to add -Wl,--no-as-needed to CFLAGS
#  This is the current default in configure (to use it)
#  Comment the next line if you do not want this, or use --without-dso
NEMO_CFLAGS1 = -Wl,--no-as-needed
```

**Comment by teuben** [comment]
This must be an environment issue.  On two of my cases I didn't have configure produce this option in the makedefs file. One case is 10.12 with the HPC.sourceforge.net compiler (7.1.0) and the other is 10.13 (high sierra) with the compiler via HomeBrew.
I still have some minor issues, but I did get > 200 working executables in $NEMOBIN.

It also remains to be seen if this odd option is still needed under Linux.

**Comment by teuben** [comment]
the default in configure is --with-dso, but it seems on e.g. Ubuntu 17.10 this is not needed anymore, so perhaps we should make the default to go without. If the test isntall script is used, for a mac it will already turn off this flag (dso=0).

**Comment by jcldc** [comment]
Ok great, works like a charm now on my MAC (10.13) with gcc 4.9.4 (macport)
