### ISSUE TITLE
"Direct" command missing

### ISSUE THREAD

**Issue by hkayabilisim** [teuben/nemo#12]
Hi,

I want to use the command "direct" to calculate Ewald sum for  a periodic boundary condition but I can see only its man page (in manl directory) after installation.  There is no executable "direct" in NEMO package after installation. There is a "directcode" command but it is not the command defined in the "man direct".

I also checked one of the older releases: ftp://ftp.astro.umd.edu/pub/nemo/nemo_2.4.1.tar.gz Again I couldn't file "direct" command.

Thank you
Huseyin

**Comment by teuben** [comment]
There is a "man directcode", which is part of NEMO.   But the "man direct" appears to refer to JoachimStadel's program, which appears to be part of tipsy.  Like a few other useful tools, we sometimes make an option to include this in NEMO.   Also look at :  https://github.com/N-BodyShop/tipsy

Unless you need tipsy, you could also try and use directcode.

**Comment by hkayabilisim** [comment]
Thank you for the explanation. As you indicated, I found it under N-BodyShop project.

I can also try "directcode" in NEMO but I guess it doesn't implement Ewald sum, right?

**Comment by teuben** [comment]
Directcode is a pure nbody code, no periodic boundaries. So no Ewald.
Unlike the other program, which does seem to have that option

**Comment by hkayabilisim** [comment]
Thank you for your help.
