### ISSUE TITLE
install_nemo missing native variable definition

### ISSUE THREAD

**Issue by cwegg** [teuben/nemo#25]
I think the current version of install_nemo isn't working out of the box. 
After the update of 27/12 I needed to add a line similar to 
`set native      = 0`
to install on my setup.

**Comment by teuben** [comment]
good catch, it was indeed left out. I' also advocating the new install_nemo.sh script with less confusing options that can do "everything". It's also written in bash, I've now encountered a few machines that do not have the csh installed (criminal in my opinion, but still, you'd be stuck).
A new version committed, i've also made the cfitsio option shorter.
