### ISSUE TITLE
gryfalcON (on e.g. fedora) now fails finding rpc/rpc.h

### ISSUE THREAD

**Issue by teuben** [teuben/nemo#26]
Although libtirpc-devel needs to be installed, this is still not enough to compile....
See here for solutions:
https://fedoraproject.org/wiki/Changes/SunRPCRemoval

**Comment by jcldc** [comment]
I have got falcON compiling on fedora30 after modifying Makefile by hand. I have to find a way to make this modification working with all distro.
For the record :
gyrfalcON on fedora30
```
....
....
VERSION          : 19-jun-2012 Walter Dehnen                           [3.6]
COMPILED         : Feb 17 2020, 21:08:02, with gcc-9.2.1               []
STATUS           : public version                                      []

```

**Comment by teuben** [comment]
I' ve hacked  Walter's  falcON/mkedefs file to use a file existence check, and add the appropriate tirpc compile flags. 
Ideally falcON  would use NEMO's makedefs, but that's for another time. or we cmake-ify everything.
