### ISSUE TITLE
bad BASH support: nemo_start.sh is too simple

### ISSUE THREAD

**Issue by teuben** [teuben/nemo#3]
NEMO's nemo_start (or nemo_start.csh) is ok for the csh, but the modern shell is bash and NEMO does not support this very well.

A much deeper question is, if we should consider another model, where source and binaries are decoupled and users don't need to modify their $PATH etc.etc.

**Comment by jcldc** [comment]
Yes, that's  good question. I don't use anymore csh for a long time now. I am using bash. To set up NEMO environement, I have created a **NEMORC.sh** that I source from my bash session.
We should have to continue to provide a *nemo_init.sh* and a *nemo_init.csh* that people would have to source.  Or install binaries and libraries in UNIX standard path....

**Comment by teuben** [comment]
I had all but forgotten there is is NEMO/src/scripts/mk_nemo_start.sh (which is actually a csh) script that generates this file.  The next pre-release will have simplified nemo_start files for csh and sh.

**Comment by teuben** [comment]
There is now a rudimentary counterpart of nemo_start.csh, but missing MANPATH and falcON support.

**Comment by jcldc** [comment]
Why don't you add this line in nemo_start.sh.in file  to add falcON support ?
export LD_LIBRARY_PATH=$NEMO/usr/dehnen/utils/lib:$NEMO/usr/dehnen/falcON:/ib:$LD_LIBRARY_PATH

**Comment by teuben** [comment]
I called it partial support. Of course we're not tracking any potential changed WD is doing, but so be it.
