### ISSUE TITLE
Ubuntu 20.04 LTS installation issues

### ISSUE THREAD

**Issue by teuben** [teuben/nemo#34]
Here we maintain a list of various installation issues for Ubuntu20:  [release date April 23, 2020]

- glnemo2 has dependency issues, so perhaps a special build for U20?   @jcldc

**Comment by jcldc** [comment]
Sure,
in a short while there will be a new glnemo2 with new build for every linux distro + mac

**Comment by teuben** [comment]
glnemo2:
   now should depend on libcfitsio8, libhdf5-103,

**Comment by teuben** [comment]
MANPATH had to be fixed. Using the manpath command, which luckily even exists on a mac.
