### ISSUE TITLE
falcON vs gcc 7.2 (ubuntu 17.10)

### ISSUE THREAD

**Issue by jcldc** [teuben/nemo#4]
falcON miserably fails to compile with gcc 7.2.
I have already work on this few month ago. I will make the modifications.

**Comment by jcldc** [comment]
Ok, I think that I have fixed compilation issue. Now falcON pass compilation on ubuntu 17.10 (gcc 7.2) and still compile on mageia6 (gcc 5.4.0).
- I had to downgrade g++ api by passing -std=c++03
- I fixed an "int" vs "unsigned int" issue
- I added an ugly fix on file lib/halo.cc to prevent loading $NEMOINC/strings.h but /usr/include/strings.h instead. BTW this file $NEMOINC/strings.h could lead in potential futur bug with new g++ 7.2, is it still necessary ?

 Before closing that issue, it would be great to test falcON compilation with different distro/compiler.

**Comment by teuben** [comment]
I'm going to make that strings.h an issue :-) I've run into that before. Some of the nemo include files suck, e.g. we have dprintf() now also in linux.

**Comment by teuben** [comment]
on a redhat 6 flavor gcc 4.4.7 is using, and it doesn't know the gcc option "-std=c++03"
on an ubuntu 16.04 gcc 5.4.0 is ok.

**Comment by jcldc** [comment]
I have modified again make.gcc (dehnen/util) in order to change c++ api only if gcc > 7.x. You  should not have any pbs compiling with gcc 4.4.7 (redhat 6). To be tested...

**Comment by jcldc** [comment]
ok, I have installed docker on my running mageia6 with  an ubuntu17.10 images container,  then I can compile/test NEMO without rebooting :) :) :) 
 falcON still pass compilation on both after latest modification of make.gcc

**Comment by teuben** [comment]
clean on rh7 and u16.04

**Comment by jcldc** [comment]
clean on fedora27 (gcc 7.2.1) whole NEMO + falcON

**Comment by jcldc** [comment]
clean on latest opensuse "tumbleweed" (gcc 7.2.1) whole NEMO + falcON

**Comment by teuben** [comment]
clean now on centos6 after a last fits writing problem

**Comment by teuben** [comment]
my own Ubuntu 17.10 now also clean.
