### ISSUE TITLE
NEMO include files sometimes collide with system versions (<nemo/stdinc.h>)

### ISSUE THREAD

**Issue by teuben** [teuben/nemo#5]
It's a long standing problem that some functions and include files collide with system versions.
dprintf() is now nemo_dprintf()
strings.h is suspicious

there are a number of suspicious names in $NEMOINC.

**Comment by teuben** [comment]
A good solution would be to use <nemo/strings.h>, but keep the <nemo.h>
Question is, should we fix that for 4.0

**Comment by jcldc** [comment]
There are very few files with #include "strings.h", here is the list : 
grep -r "strings.h" src
src/nbody/evolve/hackcode/treecode1/treeio.c:#include <strings.h>
src/tools/ile/ile.c:#include <strings.h>
src/tools/tr2latex/setups.h:#  include  <strings.h>
src/tools/FITSView/fits.c:# include <strings.h>
src/scripts/mycc.c:#include <strings.h>
src/kernel/yapp/x11/config.h:#include <strings.h>

  then these files can be easly changed by #include <nemo/strings>

**Comment by teuben** [comment]
so done.
