### ISSUE TITLE
falcON does not compile on clang

### ISSUE THREAD

**Issue by teuben** [teuben/nemo#50]
It seems falcon does not compile with my clang. @jcldc did you ever get this working, the make.clang file seems to originate from you. My version I just tried on Ubuntu 20.04 is 10.0.0, but U20.10 is now using version 11.0.0, haven't tried that yet.

Note the new 

./configure --enable-clang 

is broken, because flang does not like -g. So it's a manual labor of love to test this.

**Comment by jcldc** [comment]
Hi,
Yes I made it working successfully  on MacOS. 
I wrote down these note at the times I tested :

```
# From $NEMO/usr/dehnen
COMPILER=clang make
or
# during NEMO install
COMPILER=clang ./install_nemo clang=1

```
When you say "It seems falcon does not compile with my clang", it's on ubuntu ?
JC

**Comment by teuben** [comment]
yes, this is ubuntu. I didn't try on mac yet. good to know it worked, will report back here on progress.

**Comment by teuben** [comment]
indeed, it works following your recipe.   The path via configure is still flawed, only making it more clear that #48 is not solved.
clang clearly finds a lot of flaws in the code, given it's copious warnings.

Performance wise , when using clang v11.0 i get about 5.86sec, where g++ v10.2.0 gave me 5.96sec on the same machine, statistically identical.
This is the new "make bench3" where each of the codes runs in 5" on my fastest laptop.
