### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by teuben** [teuben/nemo#7]
This is all historic, but too many installation instructions are still lying around. These need to be cleaned up before the 4.0 release, since they are no doubt not all consistent.

INSTALL
README.install
src/scripts/bootstrap
make install
text/manual/*inc    (various places in the manual)

**Comment by teuben** [comment]
Except for the manual, things are a lot more uniform now. bootstrap script has been removed.

**Comment by sblinnikov** [comment]
Kubuntu 18.04 has **gcc-7**, but this does not work when compiling gyrfalcON, one needs **gcc-5**:

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 40
sudo update-alternatives --config gcc

sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 60
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 40
sudo update-alternatives --config g++

In debian 9.4 (stretch) default is **gcc-6**, so do in su mode:
echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" >> /etc/apt/sources.list.d/unstable.list
apt-get update
apt-get install -t unstable gcc-5
apt-get install -t unstable g++-5

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 40
sudo update-alternatives --config gcc

sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 60
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 40
sudo update-alternatives --config g++

Another issue arises with **mknemo mkkd95**. It works OK in debian, but in all versions of (k)ubuntu which I tried it does not find psplot routines. 
usr/kuijken/GalactICS-exp/src/Makefile.nemo  has MYFLIBS preceding *.o filenames. One has to put MYFLIBS after all *.o, then mknemo mkkd95 works OK both in debian and (k)ubuntu.

**Comment by teuben** [comment]
The makefile (which of course doesn't exist yet out of the box) has now been make install friendly. In its most simple fore a "configure" and "make build" is now able to produce a working NEMO. Users must still source the appropriate nemo_start.(c)sh file of course, but at installation this is now done behind the scenes [if you have all the packages that a default install needs[

This will be in release 4.1, planned for December 9 while visiting NEMO's birthplace.
