### ISSUE TITLE
falcON vs MacOSX vs gcc 4.9

### ISSUE THREAD

**Issue by jcldc** [teuben/nemo#9]
I had an issue to compile falcON on MacOSX using gcc 4.9.

I had to modify **utils/make.gcc** to : 
1) specify gnu compilers (gcc,g++) 
2) remove **-rdynamic** and **-march=native** from **OPTFLAGS**

with those modifications, dehnen's stuffs successfully compiled.

Note that there are no options to compile wth clang compiler (native macosx) although utils/makefile mention it.

**Comment by teuben** [comment]
should I see a new git commit on this?

**Comment by jcldc** [comment]
well nope... I didn't commit, it's too new. I need some feedback from others combo macosx/gcc. I don't know if the issue is specific to gcc 4.9 or to macosx. Do you have some mac machines to see how it behaves during falcON compilation ?
 Moreover, gnu gcc is not the standard compiler on macosx, it must be installed. Well, it's always a pain to compile on mac....

**Comment by jcldc** [comment]
I did commit some changes to fix the compilation issue.
These modifications detect OS type and remove/add some options regarding to Linux or Darwin architecture. (need to be tested with different compilers, right now it works with gcc 4.9)

**Comment by teuben** [comment]
since Walter has given me the blessing to maintain falcON in nemo, since his private version has diverged sufficiently now,  "we" can hack we want in  falcon. See also #18 where I hacked away a bug.

**Comment by jcldc** [comment]
Hi,
ok good news !
btw I have falcON working with python ;)

**Comment by teuben** [comment]
Heads up:    the default g++ compiler on fedora33 (gcc 10) seems to not like some C++ constructs. Might need to be finetuned with some -std= setting?

**Comment by jcldc** [comment]
Hi, did you try since I have merged clang branch into master (1h ago) ?

**Comment by teuben** [comment]
No, I did it last night!   That virtualbox is now locked up with something else, but I will shortly and report back here. Maybe you found the same errors as me. What OS were you using?

**Comment by jcldc** [comment]
Well I was working on clang (ubuntu 20.014) , but I had to modify some Dehnen's files to make them compiled. So it worth to try with gcc 10.
Let me know it if does not work. I will try from a docker fedora33

**Comment by teuben** [comment]
Worthwhile to know are the files in $NEMO/src/scripts/linux  - they are reminders what the package names are on the various flavors of linux. Usually only pgplot is important for me (which is a pain on redhat flavors). For you, compile with the default configure, since for such testing on your --with-yapp=ps (the default) is sufficient.    I now have some tools that need hdf, hdf5, cfitsio and netcdf.  Optionals are fftw3 and gsl   :-)

**Comment by jcldc** [comment]
ok found the error for fedora33 about options missing options when compiling Dehnen with gcc >= 10.x
Gonna fix it

**Comment by teuben** [comment]
looks like we can close this issue now. agree?

**Comment by jcldc** [comment]
Y.E.S
